- name: haproxy configuration playbook
  hosts: haproxy
  become: yes
  tasks: 
    - name: installation
      package:
        name: haproxy
    - template:
        dest: "/etc/haproxy/haproxy.cfg"
        src: "/home/alakhel/haproxy/haproxy.cfg"
    - service:
        name: haproxy
        state: restarted

