- name: haproxy configuration playbook
  hosts: haproxy-aws
  become: yes
  tasks: 
#    - name: installation
#      package:
#        name: haproxy
    - template:
        dest: "/etc/hapee-2.4/hapee-lb.cfg"
        src: "./haproxy.cfg"
    - service:
        name: hapee-2.4-lb
        state: reloaded

